doc8/__main__.py
doc8/main.py

Add a '__main__.py' file, which will allow us to call 'doc8' like so:
$ python -m doc8
Some noise is removed from the 'main.py' module.
Change-Id: I6c9b2e13085c20de755d708af3ff7d047be4befd

Allow doc8 to be called as a module

---

requirements.txt

If you run doc8 on a sphinx source dir without sphinx installed and if
the source dir has code blocks, doc8 will throw
D000 Cannot analyze code. Pygments package not found.
This shows up in minimized virtualenvs. It turns out you don't need
sphinx or the project in question installed to run doc8.

Add Pygments to the requirements list

---

.pre-commit-hooks.yaml

Allows user to add doc8 as a pre-commit hook.

Add pre-commit hook definition

---

README.rst
doc/source/index.rst
doc/source/usage.rst
doc8/__init__.py
doc8/main.py
doc8/tests/test_main.py
test-requirements.txt

Currently the checks can only be run via the command line, or by tricking `doc8.main.main` (eg by patching sys.argv).
This patch refactors `doc8.main` to add `doc8.doc8(**options)`, a function to run the tests directly from within another Python script (eg as a unit test). The results are available as a text string report in the same format as now, or as an array of the parts of each error. For example:
from doc8 import doc8
result = doc8(ignore_path=['.tox'])
if result.total_errors > 0:
print(f"{result.total_errors} errors in {result.files_selected} files:")
print(result.report())
The implementation makes minimal changes to the existing functions, to ensure backwards compatibility in case anyone is currently using them from their own code.
There were no tests covering `doc8.main`, so …

Add support for running directly from Python

---

doc8/checks.py

This is valid in Sphinx mode.
Change-Id: Ia6ab06c12bb48142995d90c1a803a739e7e92eac
Signed-off-by: Stephen Finucane <stephen@that.guru>
Fixes: #26

Ignore 'label' option for 'math' directive

---

doc8/checks.py

Sphinx allows the :caption: option on code-blocks, but doc8 is flagging that as an error.
For instance, this renders fine under Sphinx, but doc8 currently does not like it:
```restructuredtext
.. code-block:: bash
:caption: doc8 throws an error on caption in code-blocks, even though Sphinx accepts them.
echo "Let's fix this"
```
This pull request is to change this behavior.

Accept the :caption: option on code-block directives in Sphinx

---

doc8/checks.py

This is valid in Sphinx mode.
Fixes #31

Ignore 'nowrap' option for 'math' directive

---

doc8/checks.py

This fixes https://github.com/adamtheturtle/sphinx-substitution-extensions/issues/107

Accept the :substitutions: option on code-block directives in Sphinx

---

.pre-commit-hooks.yaml

Since the doc8 output includes a summary footer, this appears multiple times if pre-commit has run multiple copies of doc8 in parallel.
(This change would also be recommended if doc8 had its own multi-threading support, but I am unsure if that is the case)

Turn off pre-commit's automated multiprocessing

---

README.rst
doc8/main.py
doc8/parser.py
doc8/tests/test_main.py
requirements.txt

Always fall back to UTF-8.
Fixes: #18

Remove chardet based input encoding detection

---

doc8/checks.py
doc8/parser.py
doc8/tests/test_checks.py

This PR addresses issue #33. 
Files with Windows line endings (CRLF, \\r\\n) raise  `D004` (Literal carriage return) errors (which is OK), but also `D002` (trailing whitespace) and they can also rise `D001` (line too long).
With this PR
- Windows and legacy Mac line endings (CRLF or CR, respectively) will still be flagged as D004 (Literal carriage return)
- but they will not be flagged as trailing whitespace (D002)
- they will not raise a "line too long" error (D001)
- and they will not raise a "No newline at end of file" (D005)
This allows users that have Windows line endings to turn off detection of `D004` and use `doc8` to check their text files.
Rationale:
The standard of a `git` installation on Windows is that line endings in text files are converted to CRLF in the local copy. There …

Handling of Windows (and legacy Mac) line endings

---

doc8/main.py
test-requirements.txt

This pull request
- adds support for reading a doc8 configuration from a ``pyproject.toml`` file and
- removes deprecated function ``readfp`` by ``read_file``
Details:
- Reading from ini-files has not been changed, except for removing the deprecated function call to a non-deprecated one
- The ``pyproject.toml`` file is only taken into account if the toml package is available.
- If a configuration file is passed as argument and the path is not a file, it is ignored and warning is printed. No other configuration files are taken into account, therefore the default configuratoin is used.

add support for reading doc8 config from pyproject.toml file

---

doc8/checks.py

There are several options in the "code-block" which are valid in Sphinx: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=linenos#directive-code-block.
This should resolve all of the issues in #30.

Ignoring several labels for "code-block" directive.

---

README.rst

Hi, just for clarity I thought the pyproject configuration spec could be more verbose. This PR adds info on the assumed configuration section and the fact that the `toml` library needs to be installed.

Clarify pyproject.toml configuration

---

README.rst
src/doc8/main.py

Also looks for for config at `.config/doc8.ini` as this would allow users to declutter their root of their projects.

Add ability to load .config/doc8.ini

---

.pre-commit-config.yaml
README.rst
src/doc8/main.py
test-requirements.txt

Replace the use of the `toml` package with `tomli`.  The `toml` package
is no longer maintained and does not support TOML 1.0.

Use tomli to read .toml files

---

src/doc8/main.py
src/doc8/tests/test_main.py

This PR converts arguments loaded from a `pyproject.toml` file into the internal representation used for all other argument sources.  This conversion assumes the argument values in `pyproject.toml` take advantage of TOML types instead of using strings alone.  For example, while `doc8.ini` might have 
```
[doc8]
ignore-path = foo,bar
```
An equivalent `pyproject.toml` would have the following:
```
[tool.doc8]
ignore-path = [
"foo",
"bar",
]
```

Normalize arguments loaded from pyproject.toml (#75)

---

pyproject.toml

In response to https://github.com/PyCQA/doc8/issues/91#issuecomment-1195509689

Remove pip from `pyproject.toml`

---

README.rst
setup.cfg
src/doc8/main.py

Starting with 3.11 Python has a build-in library for parsing TOML, called `tomllib`. With this PR, tomli no longer needs to be installed when using python 3.11 to parse a pyproject.toml.

Make toml support implicit

---

.github/workflows/release.yml

Apparently dependabot failed to propose new versions for this likely because original tag did not exist.

Fix action version

---

src/doc8/checks.py

Fixes #115
Where do you do unit tests for individual checks? I can’t find any!

Allow PEP links with anchors

---

.github/workflows/release.yml

Refs: #124
Since the workflow only triggers on published release, this code won't be exercised until the next release.
Must have been missed when #111 did the same for a few lines below.

fix: update action version

---

README.rst

As the syntax differs from the .ini files it is helpful to also add an example for pyproject.toml files.
Also see https://github.com/PyCQA/doc8/issues/145#issuecomment-1944129330

Add example for pyproject.toml config

---

.gitignore
src/doc8/main.py

Fix absolute paths not considered for `ignore-path-errors` option

---

pyproject.toml

docutils 0.21.2 still emits the relevant deprecation warnings, but has not removed the classes.

bump docutils support

---

.github/workflows/tox.yml
.pre-commit-config.yaml
pyproject.toml
src/doc8/main.py

Attempting to resolve a continuous integration failure observed after opening #160.

ci: update to `coactions/dynamic-matrix` v3 (latest)

---

CONTRIBUTING.rst

Relates-to PyCQA/pycodestyle#1236

docs: update meta.pycqa.org URL
